name: hab_prediction
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base>=4.2.3
  - r-tidyverse>=2.0.0
  - r-renv>=v0.16.0
  - r-here>=v0.1
  - r-raster>=v3.5_21
  - r-sf>=v1.0_7
  - r-tidymodels>=v1.0.0
  - r-themis>=v1.0.0
  - r-janitor>=v.2.1.0
  - r-glmnet>=v4.1
  - r-rgdal>=v1.5_32
  - r-exactextractr>=v0.9.1
  - r-gt>=v0.8.0
  - r-gtsummary>=v1.7.0
  - r-viridis>=0.6.2
  - wget=1.20.3
  - snakemake=7.18.2
  - graphviz=6.0.1
  - coreutils>=9.1
  - requests>=2.28
